192 update user profile ui
xorum-io/codeforces_watcher pull request #197
Opened 2020-09-09 13:04 UTC by MatyashDen

2020-09-09 19:25 UTC, yevhenii-kanivets requested changes
Doesn't compile on my side 😢 Missing arguments in `DatabaseQueries.insert`.

2020-09-09 19:25 UTC, yevhenii-kanivets commented on app/src/main/java/com/bogdan/codeforceswatcher/features/users/UserActivity.kt
> +        firstName == null -> lastName!!
`?.orEmpty()` or `?: ""` and the same for all new `!!`. Let's not risk crashing the app.

2020-09-09 19:25 UTC, yevhenii-kanivets commented on common/src/commonMain/sqldelight/io/xorum/codeforceswatcher/6.sqm
> +ALTER TABLE DbUser ADD COLUMN contribution INTEGER;
Oups, will be needed to merged cautiously.

2020-09-10 08:18 UTC, MatyashDen commented
@yevhenii-kanivets 
Oops, forgot to add all files to git

2020-09-10 10:41 UTC, yevhenii-kanivets approved these changes
**it happens! Good now 👍

2020-09-10 10:44 UTC, merged