#229. Implement sign up screen.
xorum-io/codeforces_watcher pull request #245
Opened 2020-12-29 12:24 UTC by bogdan-evtushenko

2020-12-30 08:22 UTC, yevhenii-kanivets requested changes
Almost perfect 👍 Just a few minor points:
- "Sign Up" button should have disabled state until "privacy policy" isn't agreed
- Links to policy and terms seems to be not clickable

2020-12-30 08:22 UTC, yevhenii-kanivets commented on app/src/main/java/com/bogdan/codeforceswatcher/features/auth/SignUpActivity.kt
> +            checkbox.isChecked.not() -> store.dispatch(AuthRequests.SignUp.Failure(getString(R.string.agree_to_the_privacy_policy).toMessage()))
`.not()` is considered a bad practice (even though I like it too), so it's more common to use `!`.

2020-12-30 08:22 UTC, yevhenii-kanivets commented on app/src/main/java/com/bogdan/codeforceswatcher/util/Strings.kt
> +fun SpannableString.colorSubstring(l: Int, r: Int, color: Int) {
Shouldn't it be `private`?

2020-12-30 08:22 UTC, yevhenii-kanivets commented on app/src/main/java/com/bogdan/codeforceswatcher/util/Strings.kt
> +fun String.colorLinkTagPart(): SpannableString {
Name IMHO can be simplified to `linked()`.

2020-12-30 08:22 UTC, yevhenii-kanivets commented on common/src/commonMain/kotlin/io/xorum/codeforceswatcher/features/auth/AutghReducer.kt
> +
Nitpick: don't like this empty line.

2020-12-30 08:22 UTC, yevhenii-kanivets commented on common/src/commonMain/kotlin/io/xorum/codeforceswatcher/features/auth/AutghReducer.kt
> +                    signUpStatus = AuthState.Status.DONE,
Nice 👍

2020-12-30 08:57 UTC, bogdan-evtushenko commented on app/src/main/java/com/bogdan/codeforceswatcher/util/Strings.kt
> +fun SpannableString.colorSubstring(l: Int, r: Int, color: Int) {
Nope, it's used in a few more cases.

2020-12-31 08:46 UTC, yevhenii-kanivets approved these changes
Thanks!

2020-12-31 09:04 UTC, merged