358 android users screen
xorum-io/codeforces_watcher pull request #389
Opened 2021-11-24 15:20 UTC by kerymov

2021-11-27 16:10 UTC, yev-kanivets requested changes
Code looks good 👍 But I'm not sure how should I test it functionally, because I have a crash right on the app launch - `UsersFragment` can't access views through binding.

2021-11-27 18:33 UTC, kerymov commented on app/build.gradle
> +    implementation 'androidx.appcompat:appcompat:1.3.1'
Yes, everything is OK.

2021-11-27 18:33 UTC, kerymov commented
It's strange that the application crashes, I don't have such problems🤔. Which device did you use for the test?

2021-11-27 18:40 UTC, kerymov commented
Maybe the last commit will fix it?

2021-11-28 09:18 UTC, yev-kanivets approved these changes
Well, looks like I've already had this branch locally and `checkout` didn't fetch the updates as it would do for the new remote branch. So I tested some old version 🤦 Looks good now 👍 

The only problem is that I see some lags when scrolling, but probably that's because of interoperability between epoxy and Jetpack Compose. Just to be clear, the end goal is to migrate the whole screen to Jetpack Compose. Do you need a separate task for it? Or do you plan to do it when all cards are migrated to Jetpack Compose?

2021-11-28 09:18 UTC, yev-kanivets commented on app/src/main/java/com/bogdan/codeforceswatcher/features/users/UserItem.kt
> +    val avatar = if (user.avatar == "https://userpic.codeforces.org/no-avatar.jpg") {
Such (computed) fields are usually moved to come after all usual fields.

2021-11-28 16:37 UTC, kerymov commented
In my opinion it's better to migrate all cards first.

2021-11-28 16:39 UTC, merged